
server:
  port: 10030

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/

spring:
  application:
    name: zuul

zuul:
  routes:
    consumer:
      path: /api/v1/demo/get
      service-id: fetcher
